export const dummy = [
  {
    id: 1,
    type: "movie",
    title: "헤어질 결심",
    poster: "img/poster/poster_헤어질결심.jpg",
    date: "2022.06.29",
    rating: 4,
    platforms: ["넷플릭스", "왓챠", "웨이브", "티빙", "디즈니플러스"],
    genre: ["로맨스", "드라마", "스릴러"],
    director: "박찬욱",
    production: "모호필름",
    distributor: "CJ ENM",
    ageRating: "15",
    runningTime: 138,
    youtube: "https://www.youtube.com/embed/i50tT8n9fp8?si=MBFIC67575e8x7h7",
    plot: "산 정상에서 추락한 한 남자의 변사 사건. 담당 형사 '해준'(박해일)은 사망자의 아내 '서래'(탕웨이)와 마주하게 된다. 남편의 죽음 앞에서 특별한 동요를 보이지 않는 '서래'. 경찰은 보통의 유가족과는 다른 '서래'를 용의선상에 올린다. '해준'은 사건 당일의 알리바이 탐문과 신문, 잠복수사를 통해 '서래'를 알아가면서 그녀에 대한 관심이 점점 커져가는 것을 느낀다.",
    stillcuts: [
      "img/stillcut/stillcut_헤어질결심1.jpg",
      "img/stillcut/stillcut_헤어질결심2.jpg",
      "img/stillcut/stillcut_헤어질결심3.jpg",
      "img/stillcut/stillcut_헤어질결심4.jpg",
      "img/stillcut/stillcut_헤어질결심5.jpg",
    ],
  },
  {
    id: 2,
    type: "movie",
    title: "어쩔수가 없다",
    poster: "img/poster/poster_어쩔수가없다.jpg",
    date: "2025.09.24",
    rating: 4,
    platforms: ["넷플릭스", "왓챠", "웨이브", "other"],
    genre: ["스릴러", "코미디"],
    director: "박찬욱",
    production: "모호필름",
    distributor: "CJ ENM",
    ageRating: "all",
    runningTime: 138,
    youtube: "https://www.youtube.com/embed/S3zCe2J7Ru4",
    plot: "‘다 이루었다’는 생각이 들 만큼 삶에 만족하던 25년 경력의 제지 전문가 ‘만수’(이병헌). 아내 ‘미리’(손예진), 두 아이, 반려견들과 함께 행복한 일상을 보내던 만수는 회사로부터 돌연 해고 통보를 받는다.",
    stillcuts: [
      "img/stillcut/stillcut_어쩔수가없다1.jpg",
      "img/stillcut/stillcut_어쩔수가없다2.jpg",
      "img/stillcut/stillcut_어쩔수가없다3.jpg",
      "img/stillcut/stillcut_어쩔수가없다4.jpg",
    ],
  },
  {
    id: 3,
    type: "movie",
    title: "해피엔드",
    poster: "img/poster/poster_해피엔드.jpg",
    date: "2025.04.30",
    rating: 5,
    platforms: ["넷플릭스", "왓챠", "웨이브", "티빙"],
    genre: ["드라마"],
    director: "네오 소라",
    production: "영화사 진진",
    distributor: "CJ ENM",
    ageRating: "15",
    runningTime: 138,
    youtube: "https://www.youtube.com/embed/FrgrtY7ijgU",
    plot: "점멸등이 일렁이는 근미래의 도쿄. 음악에 빠진 고등학생 ‘유타’와 ‘코우’는 친구들과 함께 자유로운 나날을 보낸다. 동아리방을 찾아 늦은 밤 학교에 잠입한 그들은 교장 ‘나가이’의 고급 차량에 발칙한 장난을 치고, 분노한 학교는 AI 감시 체제를 도입한다. 그날 이후 그들을 둘러싼 모든 것이 조금씩 달라지기 시작하는데…",
    stillcuts: [
      "img/stillcut/stillcut_해피엔드1.jpg",
      "img/stillcut/stillcut_해피엔드2.jpg",
      "img/stillcut/stillcut_해피엔드3.jpg",
      "img/stillcut/stillcut_해피엔드4.jpg",
    ],
  },
  {
    id: 4,
    type: "movie",
    title: "괴물",
    poster: "img/poster/poster_괴물.jpg",
    date: "2024.11.07",
    rating: 5,
    platforms: ["넷플릭스", "티빙", "왓챠", "웨이브"],
    genre: ["드라마"],
    director: "고레에다 히로카즈",
    production: "사카모토 유지",
    distributor: "(주)NEW",
    ageRating: "12",
    runningTime: 127,
    youtube: "https://www.youtube.com/embed/5rpYSPVJZmA",
    plot: "싱글맘 사오리(안도 사쿠라)는 아들 미나토(쿠로카와 소야)의 행동에서 이상 기운을 감지한다. 용기를 내 찾아간 학교에서 상담을 진행한 날 이후 선생님과 학생들의 분위기가 심상치 않게 흐르기 시작하고. “괴물은 누구인가?” 한편 사오리는 친구들로부터 따돌림을 당하고 있는 미나토의 친구 요리(히이라기 히나타)의 존재를 알게 되고 자신이 아는 아들의 모습과 사람들이 아는 아들의 모습이 다르다는 사실을 어렴풋이 깨닫는데… 태풍이 몰아치던 어느 날, 아무도 몰랐던 진실이 드러난다.",
    stillcuts: [
      "img/stillcut/stillcut_괴물1.jpg",
      "img/stillcut/stillcut_괴물2.jpg",
      "img/stillcut/stillcut_괴물3.jpg",
      "img/stillcut/stillcut_괴물4.jpg",
    ],
  },
  {
    id: 5,
    type: "movie",
    title: "세계의 주인",
    poster: "img/poster/poster_세계의주인.jpg",
    date: "2025.10.22",
    rating: 5,
    platforms: ["other", "티빙", "넷플릭스"],
    genre: ["드라마"],
    director: "윤가은",
    production: "㈜바른손이앤에이",
    distributor: "㈜바른손이앤에이",
    ageRating: "12",
    runningTime: 119,
    youtube: "https://www.youtube.com/embed/IqpOfYlTQ54",
    plot: "반장, 모범생, 학교 인싸인 동시에 연애가 가장 큰 관심사인 열여덟 ‘이주인’. 어느 날, 반 친구 ‘수호’가 제안한 서명운동에 전교생이 동참하던 중 오직 ‘주인’만이 내용에 동의할 수 없다며 나 홀로 서명을 거부한다. 어떻게든 설득하려는 ‘수호’와 단호한 ‘주인’의 실랑이가 결국 말싸움으로 번지고, 화가 난 ‘주인’이 아무렇게나 질러버린 한마디가 주변을 혼란에 빠뜨린다. 설상가상, ‘주인’을 추궁하는 익명의 쪽지가 배달되기 시작하는데……. 인싸? 관종? 허언증? 거짓말쟁이?",
    stillcuts: [
      "img/stillcut/stillcut_세계의주인1.jpg",
      "img/stillcut/stillcut_세계의주인2.jpg",
      "img/stillcut/stillcut_세계의주인3.jpg",
      "img/stillcut/stillcut_세계의주인4.jpg",
    ],
  },
  {
    id: 6,
    type: "movie",
    title: "8번 출구",
    poster: "img/poster/poster_8번출구.jpg",
    date: "2025.10.22",
    rating: 5,
    platforms: ["other", "왓챠", "넷플릭스"],
    genre: ["스릴러"],
    director: "카와무라 겐키",
    production: "히라세 켄타로",
    distributor: "(주)NEW",
    ageRating: "12",
    runningTime: 95,
    youtube: "https://www.youtube.com/embed/rMhrw9QRXGQ",
    plot: "끝없이 반복되는 지하도에 갇힌 ‘헤매는 남자’, 아래의 규칙에 따라 8번 출구로 탈출해야만 한다. 1. 단 하나의 이상 현상도 놓치지 말 것. 2. 이상 현상을 발견하면 즉시 되돌아갈 것. 3. 이상 현상이 없다면 앞으로 나아갈 것. 4. 8번 출구를 통해서 밖으로 나갈 것.",
    stillcuts: [
      "img/stillcut/stillcut_8번출구1.jpg",
      "img/stillcut/stillcut_8번출구2.jpg",
      "img/stillcut/stillcut_8번출구3.jpg",
      "img/stillcut/stillcut_8번출구4.jpg",
    ],
  },
  {
    id: 7,
    type: "movie",
    title: "에브리씽 에브리웨어 올 앳 원스",
    poster: "img/poster/poster_에에올.jpg",
    date: "2023.10.12",
    rating: 5,
    platforms: ["넷플릭스", "왓챠", "웨이브", "티빙"],
    genre: ["액션", "코미디", "판타지"],
    director: "다니엘 콴",
    production: "워터홀컴퍼니(주",
    distributor: "워터홀컴퍼니(주)",
    ageRating: "15",
    runningTime: 139,
    youtube: "https://www.youtube.com/embed/vOXJySPfMJY",
    plot: "미국에 이민 와 힘겹게 세탁소를 운영하던 에블린은 세무당국의 조사에 시달리던 어느 날 남편의 이혼 요구와 삐딱하게 구는 딸로 인해 대혼란에 빠진다. 그 순간 에블린은 멀티버스 안에서 수천, 수만의 자신이 세상을 살아가고 있다는 사실을 알게 되고, 그 모든 능력을 빌려와 위기의 세상과 가족을 구해야 하는 운명에 처한다.",
    stillcuts: [
      "img/stillcut/stillcut_에에올1.jpg",
      "img/stillcut/stillcut_에에올2.jpg",
      "img/stillcut/stillcut_에에올3.jpg",
      "img/stillcut/stillcut_에에올4.jpg",
    ],
  },
  {
    id: 8,
    type: "movie",
    title: "컨택트",
    poster: "img/poster/poster_컨택트.jpg",
    date: "2017.02.02",
    rating: 5,
    platforms: ["넷플릭스", "왓챠", "웨이브", "티빙"],
    genre: ["드라마", "판타지"],
    director: "드니 빌뇌브",
    production: "유니버설 픽쳐스",
    distributor: "유니버설 픽쳐스",
    ageRating: "12",
    runningTime: 116,
    youtube: "https://www.youtube.com/embed/yYyzBN6MeUc",
    plot: "12개의 외계 비행 물체(쉘)가 미국, 중국, 러시아를 비롯한 세계 각지 상공에 등장했다. 웨버 대령(포레스트 휘태커)은 언어학 전문가 루이스 뱅크스 박사(에이미 아담스)와 과학자 이안 도넬리(제레미 레너)를 통해 외계 비행 물체(쉘) 접촉하기 시작한다. 두 사람은 18시간마다 아래쪽에서 문이 열리는 외계 비행 물체(쉘) 내부로 진입해 정체 모를 생명체와 마주하게 되고, 이들은 15시간 내 그들이 지구에 온 이유를 밝혀내야 하는데...",
    stillcuts: [
      "img/stillcut/stillcut_컨택트1.jpg",
      "img/stillcut/stillcut_컨택트2.jpg",
      "img/stillcut/stillcut_컨택트3.jpg",
    ],
  },

  // ===== 드라마 =====

  {
    id: 9,
    type: "drama",
    title: "서울 자가에 대기업 다니는 김부장 이야기",
    poster: "img/poster/poster_대기업다니는김부장.jpg",
    date: "2025.10.25. ~ 2025.11.30",
    rating: 4,
    platforms: ["other", "넷플릭스", "웨이브", "왓챠"],
    genre: ["드라마"],
    director: "",
    production: "",
    distributor: "JTBC",
    ageRating: "15",
    runningTime: 12,
    youtube: "https://www.youtube.com/embed/d_gczA53m8U",
    plot: "자신이 가치 있다고 생각한 모든 것을 한순간에 잃어버린 한 중년 남성이 긴 여정 끝에 마침내 대기업 부장이 아닌 진정한 본인의 모습을 발견하게 되는 이야기를 그린 드라마",
  },
  {
    id: 10,
    type: "drama",
    title: "신사장 프로젝트",
    poster: "img/poster/poster_신사장프로젝트.jpg",
    date: "2025.09.15 ~ 2025.10.28",
    rating: 5,
    platforms: ["other", "티빙", "웨이브"],
    genre: ["코미디", "드라마"],
    director: "",
    production: "",
    distributor: "tvN",
    ageRating: "15",
    runningTime: 12,
    youtube: "https://www.youtube.com/embed/hiRjE15ht1g",
    plot: "전 레전드 협상가, 현 치킨집 사장? 미스터리한 비밀을 가진 신사장이 편법과 준법을 넘나들며 사건을 해결하고 정의를 구현해 내는 분쟁 해결 히어로 드라마",
  },
  {
    id: 11,
    type: "drama",
    title: "태풍상사",
    poster: "img/poster/poster_태풍상사.jpg",
    date: "2025.10.11 ~ 2025.11.30",
    rating: 5,
    platforms: ["other", "티빙", "넷플릭스"],
    genre: ["액션", "드라마"],
    director: "",
    production: "",
    distributor: "tvN",
    ageRating: "15",
    runningTime: 16,
    youtube: "https://www.youtube.com/embed/VjwwHK1aWS4",
    plot: "1997년 IMF. 직원도, 돈도, 팔 것도 없는 무역회사의 사장이 되어버린 초보 상사맨 ‘강태풍’의 고군분투 성장기",
  },
  {
    id: 12,
    type: "drama",
    title: "달까지 가자",
    poster: "img/poster/poster_달까지가자.jpg",
    date: "2025.09.19 ~ 2025.10.31",
    rating: 5,
    platforms: ["other", "쿠팡플레이", "웨이브"],
    genre: ["코미디", "드라마"],
    director: "",
    production: "",
    distributor: "MBC",
    ageRating: "15",
    runningTime: 12,
    youtube: "https://www.youtube.com/embed/fSsIkhDXc20",

    plot: "월급만으론 생존할 수 없는 흙수저 세 여자가 코인 투자에 뛰어들며 벌어지는 하이퍼리얼리즘 생존기",
  },
  {
    id: 13,
    type: "drama",
    title: "언내추럴",
    poster: "img/poster/poster_언내추럴.jpg",
    date: "2018.01.12 ~ 2018.03.16",
    rating: 5,
    platforms: ["넷플릭스", "왓챠", "웨이브", "티빙"],
    genre: ["드라마", "스릴러"],
    director: "",
    production: "",
    distributor: "일본 TBS",
    ageRating: "15",
    runningTime: 10,
    youtube: "https://www.youtube.com/embed/HksIP72Rpvo",
    plot: "주인공과 동료들이 부자연스러운 사인으로 죽음에 이른 시체들의 억울한 원인을 규명해가는 미스터리 의학 드라마",
  },
  {
    id: 14,
    type: "drama",
    title: "워킹데드 시즌11",
    poster: "img/poster/poster_워킹데드.jpg",
    date: "2021.08.22 ~ 2022.11.21",
    rating: 5,
    platforms: ["넷플릭스", "디즈니플러스"],
    genre: ["스릴러", "드라마"],
    director: "",
    production: "",
    distributor: "AMC",
    ageRating: "15",
    runningTime: 24,
    youtube: "https://www.youtube.com/embed/EXr85xCjKrI",
    plot: "좀비로 가득한 세상에서 살아남은 생존자들의 사투를 그린 드라마",
  },
  {
    id: 15,
    type: "drama",
    title: "모던패밀리 시즌11",
    poster: "img/poster/poster_모던패밀리.jpg",
    date: "2020.04.08 종영",
    rating: 5,
    platforms: ["디즈니플러스", "왓챠", "웨이브"],
    genre: ["코미디", "드라마"],
    director: "",
    production: "",
    distributor: "CJ ENM",
    ageRating: "15",
    runningTime: 24,
    youtube: "https://www.youtube.com/embed/KmmmN3TUCqE",
    plot: "로스앤젤레스에 사는 프리쳇 가족(재혼가족, 의붓자녀, 한부모가정 등)과 그 주변의 다양한 가족들이 겪는 일상과 갈등, 화해를 유머러스하게 다루는 드라마",
  },

  {
    id: 16,
    type: "drama",
    title: "베이비 레인디어",
    poster: "img/poster/poster_베이비레인디어.jpg",
    date: "2024.04.11",
    rating: 5,
    platforms: ["넷플릭스"],
    genre: ["스릴러", "드라마"],
    director: "",
    production: "",
    distributor: "넷플릭스",
    ageRating: "15",
    runningTime: 7,
    youtube: "https://www.youtube.com/embed/eafm1gB6SCM",
    plot: "되는 일이라곤 없던 코미디언이 심리적으로 취약한 여성에게 친절을 베푼다. 그 순간, 두 사람의 삶을 동시에 무너뜨릴 수 있는 숨 막히는 집착이 시작된다.",
  },
  {
    id: 17,
    type: "drama",
    title: "조립식 가족",
    poster: "img/poster/poster_조립식가족.jpg",
    date: "2024.10.09 ~ 2024.11.27",
    rating: 5,
    platforms: ["티빙", "other"],
    genre: ["로맨스", "드라마"],
    director: "",
    production: "",
    distributor: "JTBC",
    ageRating: "15",
    runningTime: 16,
    youtube: "https://www.youtube.com/embed/9Ua6hLYGQQ0",
    plot: "10년은 가족으로 함께 했고, 10년은 남남으로 그리워했던 세 청춘이 다시 만나 펼쳐지는 로맨스",
  },
  {
    id: 18,
    type: "drama",
    title: "중쇄를 찍자!",
    poster: "img/poster/poster_중쇄를찍자.jpg",
    date: "2016.04.12",
    rating: 5,
    platforms: ["넷플릭스", "왓챠", "웨이브", "티빙", "other"],
    genre: ["로맨스", "드라마"],
    director: "",
    production: "",
    distributor: "일본 TBS",
    ageRating: "12",
    runningTime: 10,
    youtube: "https://www.youtube.com/embed/4WkHQWpE8OQ",
    plot: "주간 만화 매거진 편집부에 취직한 주인공이 만화 매거진을 팔기 위해 동료들과 함께 고군분투하는 이야기를 담은 드라마",
  },

  //밸런스게임
  {
    id: 101,
    type: "movie",
    title: "겨울왕국",
    poster: "img/poster/poster_겨울왕국.jpg",
    date: "2013.01.16",
    rating: 5,
    platforms: ["디즈니플러스", "넷플릭스", "티빙"],
    genre: ["애니메이션", "판타지"],
    director: "크리스 벅, 제니퍼 리",
    production: "월트 디즈니 애니메이션 스튜디오",
    distributor: "월트 디즈니 컴퍼니 코리아",
    ageRating: "all",
    runningTime: 102,
    youtube: "https://www.youtube.com/embed/9lqZM7G1ZiM",
    plot: "마법 같은 얼음 능력을 가진 엘사로 인해 아렌델 왕국에 영원한 겨울이 찾아온다. 동생 안나는 언니 엘사를 찾아 모험을 떠나고, 진정한 사랑과 용기의 의미를 깨닫게 된다.",
    stillcuts: [
      "img/stillcut/stillcut_겨울왕국1.jpg",
      "img/stillcut/stillcut_겨울왕국2.jpg",
      "img/stillcut/stillcut_겨울왕국3.jpg",
      "img/stillcut/stillcut_겨울왕국4.jpg",
    ],
  },
  {
    id: 102,
    type: "movie",
    title: "가디언즈",
    poster: "img/poster/poster_가디언즈.jpg",
    date: "2012.11.28",
    rating: 4,
    platforms: ["넷플릭스", "티빙", "웨이브", "라프텔"],
    genre: ["애니메이션", "판타지"],
    director: "피터 램지",
    production: "드림웍스 애니메이션",
    distributor: "UPI 코리아",
    ageRating: "all",
    runningTime: 97,
    youtube: "https://www.youtube.com/embed/aPLiBxhoug0",
    plot: "산타, 부활절 토끼, 이빨 요정 등 전설 속 영웅들이 악당 피치로부터 아이들의 꿈을 지키기 위해 힘을 합친다.",
    stillcuts: [
      "img/stillcut/stillcut_가디언즈1.jpg",
      "img/stillcut/stillcut_가디언즈2.jpg",
      "img/stillcut/stillcut_가디언즈3.jpg",
      "img/stillcut/stillcut_가디언즈4.jpg",
    ],
  },
];
