export const dummy = [
  {
    id: 1,
    type: "movie",
    title: "헤어질 결심",
    poster: "img/poster/poster_헤어질결심.jpg",
    date: "2022.06.29",
    rating: 4,
    platforms: ["넷플릭스", "왓챠", "웨이브", "티빙", "디즈니플러스"],
    genre: ["로맨스", "드라마", "스릴러"],
  },
  {
    id: 2,
    type: "movie",
    title: "어쩔수가 없다",
    poster: "img/poster/poster_어쩔수가없다.jpg",
    date: "2025.09.24",
    rating: 5,
    platforms: ["other"],
    genre: ["스릴러"],
  },
  {
    id: 3,
    type: "movie",
    title: "해피엔드",
    poster: "img/poster/poster_해피엔드.jpg",
    date: "2025.04.30",
    rating: 5,
    platforms: ["넷플릭스", "왓챠", "웨이브", "티빙"],
    genre: ["로맨스", "드라마"],
  },
  {
    id: 4,
    type: "movie",
    title: "괴물",
    poster: "img/poster/poster_괴물.jpg",
    date: "2023.11.29",
    rating: 5,
    platforms: ["넷플릭스", "티빙", "왓챠", "웨이브"],
    genre: ["드라마"],
  },
  {
    id: 5,
    type: "movie",
    title: "세계의 주인",
    poster: "img/poster/poster_세계의주인.jpg",
    date: "2025.10.22",
    rating: 5,
    platforms: ["other"],
    genre: ["드라마"],
  },
  {
    id: 6,
    type: "movie",
    title: "8번 출구",
    poster: "img/poster/poster_8번출구.jpg",
    date: "2025.10.22",
    rating: 5,
    platforms: ["other"],
    genre: ["스릴러"],
  },
  {
    id: 7,
    type: "movie",
    title: "에브리씽 에브리웨어 올 앳 원스",
    poster: "img/poster/poster_에에올.jpg",
    date: "2022.10.12",
    rating: 5,
    platforms: ["넷플릭스", "왓챠", "웨이브", "티빙"],
    genre: ["액션", "코미디", "판타지"],
  },
  {
    id: 8,
    type: "movie",
    title: "컨택트",
    poster: "img/poster/poster_컨택트.jpg",
    date: "2017.02.02",
    rating: 5,
    platforms: ["넷플릭스", "왓챠", "웨이브", "티빙"],
    genre: ["드라마", "판타지"],
  },

  // ===== 드라마 =====

  {
    id: 9,
    type: "drama",
    title: "서울 자가에 대기업 다니는 김부장 이야기",
    poster: "img/poster/poster_대기업다니는김부장.jpg",
    date: "2025.10.25",
    rating: 4,
    platforms: ["other", "왓챠"],
    genre: ["드라마"],
  },
  {
    id: 10,
    type: "drama",
    title: "신사장 프로젝트",
    poster: "img/poster/poster_신사장프로젝트.jpg",
    date: "2025.09.15",
    rating: 5,
    platforms: ["other", "티빙", "웨이브"],
    genre: ["코미디", "드라마"],
  },
  {
    id: 11,
    type: "drama",
    title: "태풍상사",
    poster: "img/poster/poster_태풍상사.jpg",
    date: "2025.10.11",
    rating: 5,
    platforms: ["other", "티빙", "넷플릭스"],
    genre: ["액션", "드라마"],
  },
  {
    id: 12,
    type: "drama",
    title: "달까지 가자",
    poster: "img/poster/poster_달까지가자.jpg",
    date: "2025.09.19",
    rating: 5,
    platforms: ["other", "쿠팡플레이", "웨이브"],
    genre: ["코미디", "드라마"],
  },
  {
    id: 13,
    type: "drama",
    title: "언내추럴",
    poster: "img/poster/poster_언내추럴.jpg",
    date: "2018.01.12",
    rating: 5,
    platforms: ["넷플릭스", "왓챠", "웨이브", "티빙"],
    genre: ["드라마", "스릴러"],
  },
  {
    id: 14,
    type: "drama",
    title: "워킹데드",
    poster: "img/poster/poster_워킹데드.jpg",
    date: "2010.10.31",
    rating: 5,
    platforms: ["넷플릭스", "디즈니플러스"],
    genre: ["스릴러", "드라마"],
  },
  {
    id: 15,
    type: "drama",
    title: "모던패밀리",
    poster: "img/poster/poster_모던패밀리.jpg",
    date: "2009.09.23",
    rating: 5,
    platforms: ["디즈니플러스"],
    genre: ["코미디", "드라마"],
  },

  {
    id: 16,
    type: "drama",
    title: "베이비 레인디어",
    poster: "img/poster/poster_베이비레인디어.jpg",
    date: "2024.04.11",
    rating: 5,
    platforms: ["넷플릭스"],
    genre: ["스릴러", "드라마"],
  },
  {
    id: 17,
    type: "drama",
    title: "조립식 가족",
    poster: "img/poster/poster_조립식가족.jpg",
    date: "2024.10.09",
    rating: 5,
    platforms: ["티빙", "other"],
    genre: ["로맨스", "드라마"],
  },
  {
    id: 18,
    type: "drama",
    title: "중쇄를 찍자",
    poster: "img/poster/poster_중쇄를찍자.jpg",
    date: "2016.04.12",
    rating: 5,
    platforms: ["넷플릭스", "왓챠", "웨이브", "티빙", "other"],
    genre: ["로맨스", "드라마"],
  },
];
